### PR TITLE
Update FEATURES.md

### PR DESCRIPTION
**Pull request by theo-armour**
Add Graphing Knowledge and possible test case scenarios

### CODE REVIEW

**Review by afomi — APPROVED** [review]
Looks good to me. :shipit:

GraphQL is a query language, often for relational data.

For a graph database, check out Node4j, which does show graphs as graphs.

**Comment by theo-armour** [comment]
@afomi 

> GraphQL is a query language, often for relational data.

Agreed. But wait there's more.

As the GraphQL home page states: 

'GraphQL provides a complete and understandable description of the data in your API.' 

Most often this is depicted in a textual manner. Can and should this data also be depicted/depictable visually in 3D? In my mind, yes, GraphQL and Mind Map are different perspectives on the same territory.

It is the GraphQL  power that we want to embed in our effort.

> Node4j, 

If you mention something, kindly always check then send a link to whatever you are talking about.

I do not believe you are referring to this project: https://github.com/jtulach/node4j

**Comment by afomi** [comment]
https://neo4j.com/developer/graph-database/

**Comment by theo-armour** [comment]
@afomi 

https://neo4j.com/graph-visualization-neo4j/

image

image

They look just like mind maps to me. ;-)

So here is the challenge:

GitHub has a very cool GraphQL API. It enables near real-time no cost transactions with the GitHub severs.

Will we be able to use the GitHub GraphQL API to direct our client-side 3D mind maps so we can take a bunch of components and show and tell you how they should be assembled in 3D and then how to disassemble them and get them to recycling??  

BTW, over in Connecticut, er, connect-edit there's some fun going on with your STL files.

**Comment by afomi** [comment]
Yes, the representation of data can still be viewed as a mindmap. Node graphs are connected with edges and relational data is linked as well. Just optimal at different structures.

I'm not sure how to use GitHub GraphQL can be leveraged. It is more about the how to access resources in their api. We will need our own data store at some point, beyond using .json files hosted via GitHub.

Structuring of putting components together and disassembling can be stored anywhere, but we need to model it first.

**Pull request merged**
